C=g++
CXX=g++
CXXFLAGS=-std=c++11 -Wall -pedantic

proj3.x: in2post.cpp
	$(CXX) $(CXXFLAGS) -g -o proj3.x in2post.cpp
proj3stack.x: test_stack1.cpp
	$(CXX) $(CXXFLAGS) -g -o proj3stack.x test_stack1.cpp

clean:
	rm *.o *.x
